#!/usr/bin/env python3
"""Print, per milestone, the leaf tasks that are currently unblocked.

Python port of a-conversa's scripts/unblocked.ts.

Approach: TaskJuggler's `!`/`!!` relative-depends syntax and container-deps
inheritance are fiddly enough that we don't re-implement them — we lean on
tj3 to resolve the graph:

  1. Synthesise a temporary `.tjp` that copies `project.tjp` verbatim and
     appends an extra `taskreport` of `formats csv` with
     id/name/complete/effort/precursors columns.
  2. Run `tj3 --silent --report unblockedcsv <tempfile>`; the CSV lands in
     `report/` (the `outputdir` in project.tjp wins).
  3. Parse the CSV. tj3 has already inherited container-level depends down
     to each leaf, so a leaf row's precursor list IS the resolved direct-dep
     set.
  4. Leaves = rows that are no other row's id-prefix. Milestones = rows
     under `milestones.` (see tasks/99-milestones.tji).
  5. Per milestone, compute the gating set of leaves by walking precursors
     transitively (containers expand to their leaves; milestone-on-milestone
     precursors expand to that milestone's gating set).
  6. A gating leaf is unblocked iff its own direct precursor expansion is
     fully complete and the leaf itself is incomplete.
  7. In the full report, also print incomplete ORPHANS — leaves in no
     milestone's gating set (audit: wire to a milestone or descope).

Usage: scripts/unblocked.py [<milestone-id>]
       (accepts `m1_memory` or `milestones.m1_memory`)
"""

from __future__ import annotations

import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PROJECT_TJP = REPO_ROOT / "project.tjp"
MILESTONES_TJI = REPO_ROOT / "tasks" / "99-milestones.tji"
REPORT_DIR = REPO_ROOT / "report"
TEMP_TJP = REPO_ROOT / ".unblocked-report.tjp"
TEMP_CSV = REPORT_DIR / "UnblockedReport.csv"

EXTRA_REPORT = """

# Auto-generated by scripts/unblocked.py. Do not commit this file.
taskreport unblockedcsv "UnblockedReport" {
  formats csv
  columns id, name, complete, effort, precursors
  hidetask 0
  loadunit days
}
"""

PRECURSOR_RE = re.compile(r"\(([A-Za-z0-9_.]+)\)\s*\]->\[")
COMPLETION_RE = re.compile(r"^(\d+(?:\.\d+)?)\s*%")


@dataclass
class TaskRow:
    id: str
    name: str
    complete_pct: float
    effort_days: float
    precursor_ids: list[str]


def run_tj3() -> list[TaskRow]:
    body = PROJECT_TJP.read_text()
    TEMP_TJP.write_text(body + EXTRA_REPORT)
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    try:
        res = subprocess.run(
            ["tj3", "--silent", "--report", "unblockedcsv", str(TEMP_TJP)],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
        )
        if res.returncode != 0:
            sys.stderr.write(res.stdout or "")
            sys.stderr.write(res.stderr or "")
            raise SystemExit(f"tj3 exited with status {res.returncode}")
        return parse_csv(TEMP_CSV.read_text())
    finally:
        TEMP_TJP.unlink(missing_ok=True)


def split_csv_line(line: str) -> list[str]:
    """tj3 CSV dialect: `;`-separated, string cells `"..."`-quoted, numeric
    cells unquoted. No embedded quotes/semicolons in this corpus."""
    out: list[str] = []
    i = 0
    while i < len(line):
        if line[i] == '"':
            end = line.find('"', i + 1)
            if end < 0:
                end = len(line)
            out.append(line[i + 1 : end])
            i = end + 1
        else:
            end = line.find(";", i)
            if end < 0:
                end = len(line)
            out.append(line[i:end])
            i = end
        if i < len(line) and line[i] == ";":
            i += 1
    return out


def parse_csv(csv: str) -> list[TaskRow]:
    lines = [l for l in csv.splitlines() if l]
    rows: list[TaskRow] = []
    for line in lines[1:]:
        cells = split_csv_line(line)
        if len(cells) < 5:
            continue
        m = COMPLETION_RE.match(cells[2])
        try:
            effort = float(cells[3])
        except ValueError:
            effort = 0.0
        rows.append(
            TaskRow(
                id=cells[0],
                name=cells[1].strip(),
                complete_pct=float(m.group(1)) if m else 0.0,
                effort_days=effort,
                precursor_ids=PRECURSOR_RE.findall(cells[4]),
            )
        )
    return rows


@dataclass
class Graph:
    by_id: dict[str, TaskRow]
    children_of: dict[str, list[str]]
    leaves_of: dict[str, list[str]] = field(default_factory=dict)

    def leaves(self, task_id: str) -> list[str]:
        cached = self.leaves_of.get(task_id)
        if cached is not None:
            return cached
        if task_id not in self.children_of:
            self.leaves_of[task_id] = [task_id]
            return self.leaves_of[task_id]
        out: list[str] = []
        for child in self.children_of[task_id]:
            out.extend(self.leaves(child))
        self.leaves_of[task_id] = out
        return out


def build_graph(rows: list[TaskRow]) -> Graph:
    by_id = {r.id: r for r in rows}
    container_ids: set[str] = set()
    for r in rows:
        cur = r.id
        while True:
            dot = cur.rfind(".")
            if dot <= 0:
                break
            cur = cur[:dot]
            container_ids.add(cur)
    children_of: dict[str, list[str]] = {}
    for r in rows:
        if r.id not in container_ids:
            continue
        prefix = r.id + "."
        children_of[r.id] = [
            c.id
            for c in rows
            if c.id.startswith(prefix) and "." not in c.id[len(prefix) :]
        ]
    g = Graph(by_id=by_id, children_of=children_of)
    for r in rows:
        g.leaves(r.id)
    return g


def expand_to_leaves(g: Graph, task_id: str, milestone_ids: set[str]) -> list[str]:
    if task_id in milestone_ids:
        # Recursive milestone link inside gating-set computation — expanded
        # separately by the caller.
        return []
    return g.leaves_of.get(task_id, [task_id])


def milestone_gating_set(
    g: Graph, ms_id: str, milestone_ids: set[str], memo: dict[str, list[str]]
) -> list[str]:
    cached = memo.get(ms_id)
    if cached is not None:
        return cached
    memo[ms_id] = []  # tentative, breaks cycles
    ms = g.by_id.get(ms_id)
    if ms is None:
        return []
    seen: set[str] = set()
    out: list[str] = []
    queue: list[str] = []

    def add_leaf(leaf_id: str) -> None:
        if leaf_id in seen:
            return
        seen.add(leaf_id)
        out.append(leaf_id)
        queue.append(leaf_id)

    def expand_precursor(pre_id: str) -> None:
        if pre_id in milestone_ids:
            for leaf in milestone_gating_set(g, pre_id, milestone_ids, memo):
                add_leaf(leaf)
        else:
            for leaf in expand_to_leaves(g, pre_id, milestone_ids):
                add_leaf(leaf)

    for pre in ms.precursor_ids:
        expand_precursor(pre)
    # Transitive predecessor closure: leaves inherit container-level depends
    # whose sibling leaves gate the milestone even when not named directly.
    while queue:
        leaf = g.by_id.get(queue.pop(0))
        if leaf is None:
            continue
        for pre in leaf.precursor_ids:
            expand_precursor(pre)
    memo[ms_id] = out
    return out


def is_leaf_unblocked(g: Graph, leaf_id: str, milestone_ids: set[str]) -> bool:
    leaf = g.by_id.get(leaf_id)
    if leaf is None or leaf.complete_pct >= 100:
        return False
    for pre in leaf.precursor_ids:
        for dep_id in expand_to_leaves(g, pre, milestone_ids):
            dep = g.by_id.get(dep_id)
            if dep is not None and dep.complete_pct < 100:
                return False
    return True


def compute_orphans(
    g: Graph,
    declared: list[str],
    milestone_ids: set[str],
    gating_memo: dict[str, list[str]],
) -> list[str]:
    """Leaves in NO milestone's gating set — nothing in the plan requires
    them. Audit: wire to a milestone or descope."""
    reached: set[str] = set()
    for ms_id in declared:
        if ms_id in milestone_ids:
            reached.update(milestone_gating_set(g, ms_id, milestone_ids, gating_memo))
    orphans = [
        r.id
        for r in g.by_id.values()
        if r.id not in g.children_of
        and not r.id.startswith("milestones.")
        and r.id not in reached
    ]
    return sorted(orphans)


def read_milestone_order() -> list[str]:
    order: list[str] = []
    depth = 0
    for raw in MILESTONES_TJI.read_text().splitlines():
        line = raw.strip()
        if line.startswith("task "):
            m = re.match(r"^task\s+(\w+)", line)
            if m and depth == 1:
                order.append(f"milestones.{m.group(1)}")
        depth += raw.count("{") - raw.count("}")
    return order


def format_effort(days: float) -> str:
    if not days:
        return ""
    s = f"{days:.2f}".rstrip("0").rstrip(".")
    return f" ({s}d)"


def main() -> None:
    args = [a for a in sys.argv[1:] if a]
    filter_arg = args[0] if args else None

    rows = run_tj3()
    g = build_graph(rows)

    declared = read_milestone_order()
    milestone_ids = {ms_id for ms_id in declared if ms_id in g.by_id}

    filter_id: str | None = None
    if filter_arg is not None:
        qualified = (
            filter_arg
            if filter_arg.startswith("milestones.")
            else f"milestones.{filter_arg}"
        )
        if qualified not in milestone_ids:
            sys.stderr.write(f"unblocked: milestone not found: {filter_arg}\n")
            sys.stderr.write("Available milestones:\n")
            for ms_id in declared:
                if ms_id in milestone_ids:
                    sys.stderr.write(f"  {ms_id.removeprefix('milestones.')}\n")
            raise SystemExit(1)
        filter_id = qualified

    gating_memo: dict[str, list[str]] = {}
    lines: list[str] = []
    omitted_complete = 0

    for ms_id in declared:
        if filter_id is not None and ms_id != filter_id:
            continue
        ms = g.by_id.get(ms_id)
        if ms is None or ms_id not in milestone_ids:
            continue
        short = ms_id.removeprefix("milestones.")
        if ms.complete_pct >= 100:
            if filter_id is None:
                omitted_complete += 1
                continue
            lines += [f"{short}: {ms.name}", "  COMPLETE — milestone already 100%", ""]
            continue
        gating = milestone_gating_set(g, ms_id, milestone_ids, gating_memo)
        complete = [l for l in gating if g.by_id[l].complete_pct >= 100]
        unblocked = [
            l
            for l in gating
            if g.by_id[l].complete_pct < 100 and is_leaf_unblocked(g, l, milestone_ids)
        ]
        blocked = [
            l
            for l in gating
            if g.by_id[l].complete_pct < 100
            and not is_leaf_unblocked(g, l, milestone_ids)
        ]

        lines.append(f"{short}: {ms.name}")
        if not gating:
            lines.append("  (no gating leaves — nothing to track)")
        elif not unblocked and not blocked:
            lines.append("  ALL GATING WORK COMPLETE — milestone ready to mark")
            lines.append(f"  COMPLETE: {len(complete)} / {len(gating)} leaves")
        else:
            lines.append(f"  READY ({len(unblocked)} leaves):")
            if not unblocked:
                lines.append(
                    "    (none — every incomplete leaf still has open predecessors)"
                )
            for leaf_id in unblocked:
                lines.append(
                    f"    {leaf_id}{format_effort(g.by_id[leaf_id].effort_days)}"
                )
            lines.append(
                f"  BLOCKED (still waiting on incomplete predecessors): {len(blocked)}"
            )
            lines.append(f"  COMPLETE: {len(complete)} / {len(gating)} leaves")
        lines.append("")

    if omitted_complete > 0:
        plural = "" if omitted_complete == 1 else "s"
        lines[:0] = [f"({omitted_complete} completed milestone{plural} omitted)", ""]

    if filter_id is None:
        orphans = compute_orphans(g, declared, milestone_ids, gating_memo)
        incomplete = [o for o in orphans if g.by_id[o].complete_pct < 100]
        if incomplete:
            lines += [
                "─" * 60,
                "ORPHANS — incomplete leaf tasks no milestone transitively depends on",
                "(nothing in the plan requires them — audit: wire to a milestone or descope)",
                "(completed orphans are omitted — done work needs no triage)",
                "",
                f"  INCOMPLETE ({len(incomplete)}):",
            ]
            for orphan_id in incomplete:
                row = g.by_id[orphan_id]
                lines.append(
                    f"    {orphan_id}{format_effort(row.effort_days)}"
                    f" [{row.complete_pct:g}%]"
                )
            lines.append("")

    sys.stdout.write("\n".join(lines))
    if not lines or not lines[-1].endswith("\n"):
        sys.stdout.write("\n")


if __name__ == "__main__":
    main()
