# Pure-CMake byte-array embed (D-truetype_captions-2): turn a binary asset into a
# generated TU defining `const std::uint8_t <SYMBOL>[]` (+ `<SYMBOL>_size`), so the
# face is linked exactly as the retired glyph table was — no runtime file I/O.
#
# Invoked as a build-time custom command:
#   cmake -DINPUT=<ttf> -DOUTPUT=<cpp> -DSYMBOL=<name> -DHEADER=<hdr> -P embed_font.cmake
# so it regenerates only when the asset (or this script) changes.
file(READ "${INPUT}" _hex HEX)
string(LENGTH "${_hex}" _hexlen)
math(EXPR _bytes "${_hexlen} / 2")
# Two hex nibbles -> one `0xNN,` byte literal. One regex pass over the whole blob.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _arr "${_hex}")
set(_out "// GENERATED by cmake/embed_font.cmake from ${INPUT} - do not edit, not committed.\n")
string(APPEND _out "#include <${HEADER}>\n\n")
string(APPEND _out "namespace ace::commands {\n\n")
string(APPEND _out "extern const std::uint8_t ${SYMBOL}[] = {\n${_arr}\n};\n")
string(APPEND _out "extern const unsigned int ${SYMBOL}_size = ${_bytes}u;\n\n")
string(APPEND _out "} // namespace ace::commands\n")
file(WRITE "${OUTPUT}" "${_out}")
